apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: metallb-system
  interval: 10m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: default
      interval: 10m
