apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: cert-manager
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: default
      interval: 10m
  values:
    installCRDs: true
