apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: default
      interval: 10m
  values:
    installCRDs: true
